{"version":1,"defects":{"Warning":6,"Error":4,"Tests\\Unit\\Services\\InvoiceServiceTest::test_it_processes_invoice":3},"times":{"Warning":0.001,"Tests\\Unit\\RouterTest::testRegister":0.001,"Tests\\Unit\\RouterTest::testRouteRegister":0.001,"Tests\\Unit\\RouterTest::testThatItRegistersARoute":0.001,"Tests\\Unit\\RouterTest::test_that_it_registers_a_route":0.001,"Tests\\Unit\\RouterTest::it_registers_a_route":0.001,"Tests\\Unit\\RouterTest::test_it_registers_a_get_route":0,"Tests\\Unit\\RouterTest::test_it_registers_a_post_route":0,"Tests\\Unit\\RouterTest::test_there_are_no_routes_when_router_is_created":0,"Tests\\Unit\\RouterTest::test_it_registers_a_route":0.001,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception with data set #0":0,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception with data set #1":0,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception with data set #2":0,"Tests\\Unit\\RouterTest::test_it_throws_route_not_found_exception with data set #3":0,"Error":0,"Tests\\Unit\\RouterTest::test_it_resolves_route_from_a_closure":0,"Tests\\Unit\\RouterTest::test_it_resolves_route":0,"Tests\\Unit\\Services\\InvoiceServiceTest::test_it_processes_invoice":3.005}}